#name: Nelweg
#
#on: [push]
#
#jobs:
#  test:
#   name: Test
#   runs-on: [self-hosted]
#   steps:
#    - name: Check out code
#      uses: actions/checkout@v3
#
#    - name: Setup
#      uses: actions/setup-go@v4
#      with:
#        go-version: 1.20.3
#
#    - name: Install dependencies
#      run: go get .
#
#    - name: Test
#      run: go test -v ./...